modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="heracles"
version = "${version}"
displayName="Heracles"
authors="ThatGravyBoat"
description="Heracles is a comprehensive questing mod that allows pack makers to create tree style quests that can be distributed via the config folder for users to play and complete."

[[dependencies.heracles]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.heracles]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.heracles]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.17,)"
ordering = "NONE"
side = "BOTH"
